/**
 * UGC Multi-Scene pipeline — an Arcads/MakeUGC-style upgrade over the single
 * clip UGC mode:
 *
 *   script ─► LLM scene breakdown (hook/product/CTA beats)
 *             └─► per scene: TTS voiceover (one voice) ─► I2V/T2V clip
 *                                        └─► lip-sync mouth to TTS (optional)
 *   ──► timeline of clips + continuous voiceover (played by WavespeedVideo)
 *
 * - The LLM splits the script into 2-6 scenes, each with:
 *   - `lines`    : the spoken words (fed to TTS),
 *   - `visual`   : an image/video-generation prompt describing the character
 *                  in that setting/action (fed to the model),
 *   - `durationSec`: a suggested clip length (used only when TTS is unavailable).
 * - One voiceover is generated for the whole ad (ElevenLabs preferred,
 *   Deepgram fallback) so the voice stays identical across every cut.
 * - Each scene's video is generated by the selected UGC model (I2V when a
 *   reference image is supplied, T2V otherwise) and muted in the composition;
 *   the TTS audio is overlaid on top — exactly how the WavespeedVideo
 *   composition plays TextToVideo/MicroDrama timelines.
 *
 * All AI calls go through the shared WaveSpeed key:
 *   - LLM (OpenAI-compatible): https://llm.wavespeed.ai/v1
 *   - Video:                   https://api.wavespeed.ai/api/v3/{model}
 */

import * as fs from "fs";
import * as path from "path";
import { v4 as uuidv4 } from "uuid";
import { WavespeedClient } from "./wavespeed";
import { getUGCModel } from "./ugc-models";
import { generateSpeechWithTimestamps, AURA_VOICES } from "./deepgram";
import { DEFAULT_ELEVENLABS_VOICE_ID } from "./elevenlabs";
import { uploadAsset } from "./wavespeed-timeline";
import type { WavespeedTimelineAsset } from "./wavespeed-timeline";
import { getAspectRatioDimensions } from "../../shared/video-schema";

// === Model defaults (mirrors the MicroDrama pipeline) ===
export const UGC_LLM_MODEL = () =>
  process.env.WAVESPEED_LLM_MODEL || "deepseek/deepseek-v4-flash";

const UGC_LLM_BASE_URL = "https://llm.wavespeed.ai/v1";

// === Scene types ===
export interface UGCScene {
  idx: number;
  title: string;
  /** Spoken lines for this scene (fed to TTS). */
  lines: string;
  /** Visual prompt for the video model (character, setting, camera, action). */
  visual: string;
  /** Suggested clip length in seconds (used when TTS is unavailable). */
  durationSec: number;
}

// Deterministic fallback: chunk the script into scenes by sentence so the
// pipeline still works if the LLM is unreachable. Scenes follow the standard
// UGC beat structure (Hook → Problem → Product → Demo → Outcome → CTA).
function fallbackScenes(script: string): UGCScene[] {
  const sentences = script
    .split(/(?<=[.!?])\s+|\n+/)
    .map((s) => s.trim())
    .filter((s) => s.length > 0);

  const groups: string[][] = [];
  for (const s of sentences) {
    const last = groups[groups.length - 1];
    if (last && last.join(" ").length < 90) last.push(s);
    else groups.push([s]);
  }
  while (groups.length > 6) {
    const last = groups.pop()!;
    groups[groups.length - 1].push(...last);
  }
  const clamped = groups.slice(0, 6);

  const beatTitles = ["Hook", "Problem", "Product", "Demo", "Outcome", "CTA"];

  return clamped.map((g, i) => ({
    idx: i,
    title: beatTitles[i] || `Beat ${i + 1}`,
    lines: g.join(" "),
    visual: [
      "A person talking energetically to the camera in a selfie-style vertical shot.",
      i === 0 ? "Strong hook, punchy delivery, bright natural lighting." :
        i === clamped.length - 1 ? "Confident closer, direct call to action, warm smile." :
          "Casual, conversational tone, slight camera push-in.",
    ].join(" "),
    durationSec: Math.max(3, Math.min(8, Math.ceil(g.join(" ").split(/\s+/).length / 2.5))),
  }));
}

// === WaveSpeed LLM (OpenAI-compatible Chat Completions) ===
async function llmCall(payload: Record<string, unknown>): Promise<string> {
  const apiKey = process.env.WAVESPEED_API_KEY;
  if (!apiKey) {
    throw new Error("WAVESPEED_API_KEY environment variable is not set in your .env.local file.");
  }

  const res = await fetch(`${UGC_LLM_BASE_URL}/chat/completions`, {
    method: "POST",
    headers: {
      Authorization: `Bearer ${apiKey}`,
      "Content-Type": "application/json",
    },
    body: JSON.stringify(payload),
    signal: AbortSignal.timeout(120000),
  });

  if (!res.ok) {
    const text = await res.text();
    const err = new Error(`WaveSpeed LLM error: ${res.status} - ${text}`) as Error & { status?: number };
    err.status = res.status;
    throw err;
  }

  const data = (await res.json()) as { choices?: Array<{ message?: { content?: unknown } }> };
  const content = data.choices?.[0]?.message?.content;
  if (typeof content !== "string" || !content.trim()) {
    throw new Error("WaveSpeed LLM returned empty content.");
  }
  return content;
}

async function wavespeedLLM(
  systemPrompt: string,
  userPrompt: string,
  temperature = 0.7,
  json = false
): Promise<string> {
  const base: Record<string, unknown> = {
    model: UGC_LLM_MODEL(),
    messages: [
      { role: "system", content: systemPrompt },
      { role: "user", content: userPrompt },
    ],
    temperature,
  };

  try {
    if (json) {
      return await llmCall({ ...base, response_format: { type: "json_object" } });
    }
    return await llmCall(base);
  } catch (err) {
    const status = (err as { status?: number })?.status;
    if (json && status && status >= 400 && status < 500) {
      console.warn("[UGC Multi-Scene] LLM rejected JSON mode, retrying without response_format.");
      return await llmCall(base);
    }
    throw err;
  }
}

function extractJSON(text: string): string {
  const codeBlockMatch = text.match(/```(?:json)?\s*([\s\S]*?)```/);
  if (codeBlockMatch) return codeBlockMatch[1].trim();
  const jsonMatch = text.match(/\{[\s\S]*\}/);
  if (jsonMatch) return jsonMatch[0];
  return text.trim();
}

async function llmJSON<T>(systemPrompt: string, userPrompt: string, fallback: T): Promise<T> {
  try {
    const raw = await wavespeedLLM(systemPrompt, userPrompt, 0.7, true);
    return JSON.parse(extractJSON(raw)) as T;
  } catch (err) {
    console.warn("[UGC Multi-Scene] LLM JSON call failed, using fallback:", err);
    return fallback;
  }
}

// === Scene breakdown agent ===
const SCENE_SYSTEM_PROMPT = `You are a UGC video director and copywriter. Your job is to break a raw
script into 2-6 short "scenes" for a single-actor talking-to-camera UGC ad
(TikTok/Reels/Shorts style). Each scene becomes its own AI-generated video clip,
so it must be visually self-contained and around 3-8 seconds of speech.

Return ONLY valid JSON — no markdown, no explanation, just JSON.`;

async function breakDownScenes(
  script: string,
  images: string[],
  targetDurationSec: number,
  aspectRatio: string
): Promise<UGCScene[]> {
  const userPrompt = `Split this UGC ad script into 2-6 scenes that follow the standard UGC beat structure:
1. Hook (punchy first 1-3 seconds) → 2. Relatable problem → 3. Product appears
→ 4. Simple demo → 5. Believable outcome → 6. Natural CTA.
Adapt the number of beats to the script (a 2-scene ad = Hook + CTA; a 3-scene ad
= Hook, Product+Demo, CTA; 4-6 scenes distribute the full structure).

Script:
${script}

${images.length > 0 ? `Reference images are available (first image = the actor's face/character).\n` : ""}
Target total duration: ${targetDurationSec} seconds.
Output aspect ratio: ${aspectRatio} (mention composition suited to it).

Return a JSON object with this exact structure:
{
  "scenes": [
    {
      "title": "Hook | Problem | Product | Demo | Outcome | CTA",
      "lines": "Exactly what the actor says aloud in this scene. Keep it 2-4 sentences and the FULL text needed; it will be spoken by TTS.",
      "visual": "One detailed prompt for the video model: actor appearance/pose, setting, camera angle/movement, lighting, mood. 25-60 words. Do not mention 'text to video' or 'UGC'.",
      "durationSec": 5
    }
  ]
}

Rules:
- 2 to 6 scenes total. The sum of durationSec should roughly equal ${targetDurationSec} seconds.
- The spoken lines across all scenes must together preserve the full meaning of the script (you may tighten wording).
- Hook first (punchy), strong CTA last. Product should appear by the midpoint at the latest.
- Every scene's visual should keep the same actor consistent (same person, outfit, style).
- Keep claims honest: do NOT introduce fake testimonials, guaranteed results, income/medical claims, or fake expert endorsements that are not in the script.
- durationSec per scene: 3-8 seconds, scaled so faster speech = shorter, and total matches the target.`;

  const data = await llmJSON<{ scenes?: Array<{ title?: string; lines?: string; visual?: string; durationSec?: number }> }>(
    SCENE_SYSTEM_PROMPT,
    userPrompt,
    { scenes: fallbackScenes(script).map((s) => ({ ...s })) }
  );

  const scenes = Array.isArray(data.scenes)
    ? data.scenes.filter((s) => s && typeof s.lines === "string" && s.lines.trim())
    : [];
  if (scenes.length === 0) return fallbackScenes(script);

  return scenes.slice(0, 6).map((s, i) => ({
    idx: i,
    title: (s.title || `Scene ${i + 1}`).slice(0, 80),
    lines: (s.lines as string).trim(),
    visual: (s.visual || fallbackScenes(script)[0].visual).trim(),
    durationSec: Math.max(3, Math.min(8, Math.round(s.durationSec || 5))),
  }));
}

// === Helpers ===
async function mapWithConcurrency<T, R>(
  items: T[],
  limit: number,
  fn: (item: T, index: number) => Promise<R>
): Promise<R[]> {
  const results: R[] = new Array(items.length);
  let idx = 0;

  const worker = async () => {
    while (idx < items.length) {
      const current = idx++;
      results[current] = await fn(items[current], current);
    }
  };

  await Promise.all(new Array(Math.min(limit, items.length)).fill(0).map(() => worker()));
  return results;
}

// Group word timestamps into caption chunks (for the `text` fallback overlays).
function buildCaptionChunks(
  wordTimestamps: Array<{ word: string; start: number; end: number }>,
  maxChars = 18
): Array<{ startMs: number; endMs: number; text: string; position: string }> {
  const chunks: Array<{ startMs: number; endMs: number; text: string; position: string }> = [];
  let currentText = "";
  let currentStartMs = wordTimestamps[0] ? wordTimestamps[0].start * 1000 : 0;
  let currentEndMs = currentStartMs;

  for (const w of wordTimestamps) {
    if ((currentText + w.word).length > maxChars && currentText.trim()) {
      chunks.push({
        startMs: currentStartMs,
        endMs: currentEndMs,
        text: currentText.trim(),
        position: "center",
      });
      currentText = "";
      currentStartMs = w.start * 1000;
    }
    currentText += `${w.word} `;
    currentEndMs = w.end * 1000;
  }

  if (currentText.trim()) {
    chunks.push({
      startMs: currentStartMs,
      endMs: currentEndMs,
      text: currentText.trim(),
      position: "center",
    });
  }

  return chunks;
}

const absolutize = (url: string, baseUrl: string): string =>
  url.startsWith("/") ? `${baseUrl}${url}` : url;

// === Public pipeline ===
export interface UGCMultiSceneInput {
  prompt: string;
  images?: string[];
  model?: string;
  aspectRatio?: string;
  resolution?: string;
  voice?: string;
  targetDurationSec?: number;
  /**
   * Re-animate each scene clip's mouth to match the TTS voiceover using
   * WaveSpeed `sync/lipsync-2` (default on). Adds ~$0.05/run + ~2min per
   * scene. Requires the TTS audio to be publicly reachable (assetBaseUrl).
   */
  lipSync?: boolean;
  /** Optional explicit scene count hint (2-6). Defaults to LLM's choice. */
  sceneCount?: number;
}

export interface UGCMultiSceneOptions {
  /** Progress callback, 0-1 across the whole pipeline. */
  onProgress?: (progress: number) => void;
  /** Base URL used to absolutize relative asset paths. */
  assetBaseUrl?: string;
}

/**
 * UGC Multi-Scene pipeline: script → LLM scene breakdown → one TTS voiceover
 * → per-scene I2V/T2V clips → timeline of clips + voiceover.
 *
 * Returns a `WavespeedTimelineAsset` playable by the `WavespeedVideo`
 * composition (registered as the `UGC` Remotion composition).
 */
export async function generateUGCMultiSceneTimeline(
  input: UGCMultiSceneInput,
  options: UGCMultiSceneOptions = {}
): Promise<WavespeedTimelineAsset> {
  const { onProgress, assetBaseUrl } = options;
  const jobId = uuidv4();
  const model = getUGCModel(input.model);
  const client = new WavespeedClient();

  const images = (input.images || []).filter(Boolean);
  const aspectRatio = input.aspectRatio || model.defaultAspectRatio;
  const resolution = input.resolution || model.defaultResolution;
  const targetDurationSec = Math.min(60, Math.max(10, input.targetDurationSec || 30));
  const lipSync = input.lipSync !== false;

  // TTS provider check — multi-scene relies on a real voiceover.
  const ttsProvider = process.env.ELEVENLABS_API_KEY ? "ElevenLabs" : process.env.DEEPGRAM_API_KEY ? "Deepgram" : null;
  if (!ttsProvider) {
    throw new Error(
      "Multi-scene UGC requires a TTS provider. Set ELEVENLABS_API_KEY (preferred) or DEEPGRAM_API_KEY in .env.local."
    );
  }

  console.log(
    `[UGC Multi-Scene] Starting for job ${jobId}: model=${model.id} ratio=${aspectRatio} target=${targetDurationSec}s images=${images.length} tts=${ttsProvider}`
  );
  onProgress?.(0.02);

  // 1. LLM scene breakdown
  let scenes: UGCScene[];
  try {
    scenes = await breakDownScenes(input.prompt, images, targetDurationSec, aspectRatio);
  } catch (err) {
    console.warn("[UGC Multi-Scene] Scene breakdown failed, using fallback split:", err);
    scenes = fallbackScenes(input.prompt);
  }
  console.log(`[UGC Multi-Scene] Broke script into ${scenes.length} scenes.`);
  onProgress?.(0.1);

  // 2. One voice across all scenes
  const hasElevenLabs = Boolean(process.env.ELEVENLABS_API_KEY);
  let defaultVoice = AURA_VOICES[Math.floor(Math.random() * AURA_VOICES.length)];
  if (hasElevenLabs) {
    defaultVoice = DEFAULT_ELEVENLABS_VOICE_ID;
  }
  const selectedVoice = input.voice || defaultVoice;
  console.log(`[UGC Multi-Scene] Using voice [${selectedVoice}] for the whole ad.`);

  const tempDir = path.join(process.cwd(), "public", "assets-temp");
  if (!fs.existsSync(tempDir)) {
    fs.mkdirSync(tempDir, { recursive: true });
  }

  // 3. Per-scene TTS (sequential to keep the same voice + simple rate control)
  const sceneVoices: Array<{
    audioUrl: string;
    words: Array<{ word: string; start: number; end: number }>;
    audioEndSec: number;
    clipDurationSec: number;
  }> = [];
  for (let i = 0; i < scenes.length; i++) {
    const scene = scenes[i];
    const sceneProgress = 0.1 + (i / Math.max(1, scenes.length)) * 0.25;
    const localAudioPath = path.join(tempDir, `${jobId}-scene-${i}.mp3`);
    try {
      const wordTimestamps = await generateSpeechWithTimestamps(scene.lines, localAudioPath, selectedVoice);
      const lastWord = wordTimestamps[wordTimestamps.length - 1];
      const audioEndSec = Math.max(1.5, lastWord ? lastWord.end + 0.35 : scene.lines.split(/\s+/).length / 2.5 + 0.35);
      const audioUrl = await uploadAsset(fs.readFileSync(localAudioPath), `${jobId}-scene-${i}.mp3`, "audio/mpeg");
      // Clip length is driven by the spoken audio, clamped to the model's range.
      const clipDurationSec = Math.min(model.durationMax, Math.max(model.durationMin, Math.ceil(audioEndSec)));
      sceneVoices.push({ audioUrl, words: wordTimestamps, audioEndSec, clipDurationSec });
      console.log(`[UGC Multi-Scene] Scene ${i + 1} voiceover: ${audioEndSec.toFixed(1)}s (clip ${clipDurationSec}s).`);
    } catch (err) {
      console.warn(`[UGC Multi-Scene] TTS failed for scene ${i + 1}: ${err}`);
      sceneVoices.push({
        audioUrl: "",
        words: [],
        audioEndSec: scene.durationSec,
        clipDurationSec: Math.min(model.durationMax, Math.max(model.durationMin, scene.durationSec)),
      });
    }
    onProgress?.(sceneProgress);
  }

  // 4. Per-scene clips (parallel, non-fatal per scene)
  const clipResults = await mapWithConcurrency(scenes, 2, async (scene, i) => {
    const voice = sceneVoices[i];
    const clipDurationSec = voice.clipDurationSec;
    const videoPrompt = `${scene.visual}`;

    try {
      let clipUrl: string;
      if (images.length > 0) {
        // I2V: animate the actor's reference image in the scene's setting.
        const { resultUrl } = await client.triggerImageToVideo(
          videoPrompt,
          images[0],
          clipDurationSec,
          resolution,
          model.i2vEndpoint
        );
        clipUrl = (await client.pollPrediction(resultUrl))[0];
      } else {
        // T2V: generate the scene purely from the visual prompt.
        const { resultUrl } = await client.triggerModel(model.t2vEndpoint, {
          prompt: videoPrompt,
          aspect_ratio: aspectRatio,
          duration: clipDurationSec,
          resolution,
          generate_audio: true,
        });
        clipUrl = (await client.pollPrediction(resultUrl))[0];
      }

      // Lip-sync: warp the actor's mouth to the scene's TTS audio using
      // WaveSpeed `sync/lipsync-2` (zero-shot; cut_off trims the clip to the
      // audio length). Non-fatal — falls back to the original clip.
      if (lipSync && voice.audioUrl && assetBaseUrl) {
        try {
          const audioUrl = absolutize(voice.audioUrl, assetBaseUrl);
          console.log(`[UGC Multi-Scene] Lip-syncing scene ${i + 1} with ${audioUrl}...`);
          const { resultUrl } = await client.triggerModel("sync/lipsync-2", {
            video: clipUrl,
            audio: audioUrl,
            sync_mode: "cut_off",
          });
          const outputs = await client.pollPrediction(resultUrl, 5000, 600000);
          if (outputs[0]) {
            console.log(`[UGC Multi-Scene] Scene ${i + 1} lip-synced -> ${outputs[0]}`);
            clipUrl = outputs[0];
          }
        } catch (lipErr) {
          console.warn(`[UGC Multi-Scene] Lip-sync failed for scene ${i + 1} (using original clip): ${lipErr}`);
        }
      }

      return { videoUrl: clipUrl };
    } catch (err) {
      console.warn(`[UGC Multi-Scene] Clip generation failed for scene ${i + 1}: ${err}`);
      return null;
    }
  });

  // 5. Assemble the timeline
  const elements: Array<{ videoUrl: string; startMs: number; endMs: number }> = [];
  const audio: Array<{ startMs: number; endMs: number; audioUrl: string }> = [];
  const words: Array<{ word: string; startMs: number; endMs: number }> = [];
  let globalOffsetMs = 0;
  let anyClip = false;

  for (let i = 0; i < scenes.length; i++) {
    const clip = clipResults[i];
    const voice = sceneVoices[i];
    const clipDurationMs = voice.clipDurationSec * 1000;
    const startMs = globalOffsetMs;
    const endMs = startMs + clipDurationMs;

    if (clip) {
      anyClip = true;
      elements.push({ videoUrl: clip.videoUrl, startMs, endMs });
    }

    if (voice.audioUrl) {
      const audioEndMs = Math.min(endMs, startMs + Math.round(voice.audioEndSec * 1000));
      audio.push({ startMs, endMs: audioEndMs, audioUrl: voice.audioUrl });
    }

    for (const w of voice.words) {
      words.push({
        word: w.word,
        startMs: startMs + Math.round(w.start * 1000),
        endMs: startMs + Math.round(w.end * 1000),
      });
    }

    globalOffsetMs = endMs;
  }

  if (!anyClip) {
    throw new Error("All scenes failed to generate video clips.");
  }

  const { width, height } = getAspectRatioDimensions(aspectRatio);
  const totalDurationMs = Math.max(globalOffsetMs, 1000);
  const text = buildCaptionChunks(
    words.map((w) => ({ word: w.word, start: w.startMs / 1000, end: w.endMs / 1000 }))
  );

  const timeline: WavespeedTimelineAsset = {
    shortTitle: input.prompt.substring(0, 60),
    elements,
    text,
    audio,
    words,
    width,
    height,
  };

  if (assetBaseUrl) {
    timeline.elements = timeline.elements.map((el) => ({
      ...el,
      videoUrl: absolutize(el.videoUrl, assetBaseUrl),
    }));
    timeline.audio = timeline.audio.map((a) => ({
      ...a,
      audioUrl: absolutize(a.audioUrl, assetBaseUrl),
    }));
  }

  onProgress?.(1);
  console.log(
    `[UGC Multi-Scene] Timeline ready: ${elements.length} scenes over ${totalDurationMs}ms (${(totalDurationMs / 1000).toFixed(1)}s).`
  );
  return timeline;
}
