import * as fs from "fs";
import * as path from "path";

const rootDir = path.join(__dirname, "../src/remotion");

// Dict mapping from Japanese to English
const translationMap: Record<string, string> = {
  "スイッチ/トグル": "Switch/Toggle",
  "トグルスイッチ": "Toggle Switch",
  "ステータス": "Status",
  "設定項目": "Settings Items",
  "通知アニメーション": "Notification Animation",
  "トースト": "Toast",
  "タブアニメーション": "Tabs Animation",
  "タブヘッダー": "Tab Header",
  "タブコンテンツ": "Tab Content",
  "ナビゲーションメニュー": "Navigation Menu",
  "ナビゲーションバー": "Navigation Bar",
  "ロゴ": "Logo",
  "メニュー": "Menu",
  "アンダーライン": "Underline",
  "コンテンツエリア": "Content Area",
  "モーダルアニメーション": "Modal Animation",
  "背景コンテンツ": "Background Content",
  "バックドロップ": "Backdrop",
  "モーダル": "Modal",
  "閉じるボタン": "Close Button",
  "チェックマークアイコン": "Checkmark Icon",
  "ローディングアニメーション": "Loading Animation",
  "スピナー": "Spinner",
  "ドットローダー": "Dot Loader",
  "プログレスバー": "Progress Bar",
  "スケルトン": "Skeleton",
  "入力フォーム": "Input Form",
  "Email入力": "Email Input",
  "Password入力": "Password Input",
  "ボタン": "Button",
  "リンク": "Link",
  "ドロップダウンメニュー": "Dropdown Menu",
  "トリガー": "Trigger",
  "カードアニメーション": "Card Animation",
  "ホバーエフェクト": "Hover Effect",
  "メインカードのアニメーション": "Main Card Animation",
  "サブカードのアニメーション": "Sub Card Animation",
  "ホバーエフェクト（フレームベース）": "Hover Effect (Frame Based)",
  "背景装飾ライン": "Background Decorative Line",
  "左上のラベル": "Top-Left Label",
  "メインカード（大きく左寄り）": "Main Card (Large Left-aligned)",
  "カード内のアクセントライン": "Accent Line inside Card",
  "コンテンツエリア": "Content Area",
  "下部のタグ": "Bottom Tag",
  "サブカード（右側、小さめ、上にオフセット）": "Sub Card (Right side, smaller, offset top)",
  "右下の番号装飾": "Bottom-Right Number Decoration",
  "ボタンアニメーション": "Button Animation",
  "ホバー&クリック": "Hover & Click",
  "メインボタン": "Main Button",
  "セカンダリボタン": "Secondary Button",
  "オーロラ効果": "Aurora Effect",
  "オーロラレイヤー": "Aurora Layer",
  "ボケ効果": "Bokeh Effect",
  "流れるグラデーション": "Flowing Gradient",
  "ジオメトリックパターン": "Geometric Pattern",
  "グリッドアニメーション": "Grid Animation",
  "メッシュグラデーション": "Mesh Gradient",
  "ノイズテクスチャ": "Noise Texture",
  "パースペクティブグリッド": "Perspective Grid",
  "放射状パターン": "Radial Pattern",
  "波形背景": "Wave Background",
  "アクションタイトル": "Action Title",
  "アニメ風タイトル": "Anime Style Title",
  "ドキュメンタリー風": "Documentary Style",
  "エピックタイトル": "Epic Title",
  "大作映画風": "Blockbuster Movie Style",
  "ホラータイトル": "Horror Title",
  "ミニマリストエンディング": "Minimalist Ending",
  "ノワール風": "Noir Style",
  "ロマンスタイトル": "Romance Title",
  "SF/テック風": "Sci-Fi / Tech Style",
  "ヴィンテージ風": "Vintage Style",
  "バーチャート": "Bar Chart",
  "棒グラフ": "Column Graph",
  "ゲージメーター": "Gauge Meter",
  "スピードメーター風": "Speedometer Style",
  "ラインチャート": "Line Chart",
  "折れ線グラフ": "Line Graph",
  "パイチャート": "Pie Chart",
  "円グラフ": "Circle Graph",
  "複数のプログレス": "Multiple Progress Indicators",
  "ランキング": "Ranking",
  "リストアニメーション": "List Animation",
  "スタッツカード": "Stats Cards",
  "統計カード（非対称レイアウト）": "Statistical Cards (Asymmetric Layout)",
  "タイムライン": "Timeline",
  "時系列表示": "Chronological Timeline",
  "ブラウザアドレスバーデモ": "Browser Address Bar Demo",
  "マウスカーソル移動": "Mouse Cursor Movement",
  "クリック": "Click",
  "ドラッグ&ドロップデモ": "Drag & Drop Demo",
  "メニュー展開デモ": "Menu Expansion Demo",
  "モーダル表示デモ": "Modal Display Demo",
  "画面遷移デモ": "Page Transition Demo",
  "画面スクロールデモ": "Page Scroll Demo",
  "検索フィルターデモ": "Search Filter Demo",
  "テキスト入力デモ": "Text Input Demo",
  "ツールチップ/ポップオーバーデモ": "Tooltip / Popover Demo",
  "ステップウィザードデモ": "Step Wizard Demo",
  "ズームイン/フォーカスデモ": "Zoom-In / Focus Demo",
  "クリックリップルエフェクト": "Click Ripple Effect",
  "共通マウスカーソルコンポーネント": "Common Mouse Cursor Component",
  "ハイライトボックス": "Highlight Box",
  "効果": "Effect",
  "アニメーション": "Animation",
  "デモ": "Demo",
  "共通": "Common",
  "背景": "Background",
  "中心円": "Center Circle",
  "星空": "Starry Sky",
  "惑星": "Planet",
  "星を生成": "Generate Stars",
  "グリッチレイヤー": "Glitch Layer",
  "警告ストライプ": "Warning Stripe",
  "金属テクスチャ": "Metal Texture",
  "ボルト装飾": "Bolt Decoration",
  "縦書きテキスト": "Vertical Text",
  "静寂の美": "Beauty of Silence",
  "横書きサブテキスト": "Horizontal Subtext",
  "金色のライン装飾": "Gold Line Decoration",
  "黒いブロック": "Black Block",
  "白テキスト（黒背景上）": "White Text (on Black Background)",
  "黒テキスト（白背景上）": "Black Text (on White Background)",
  "中央の境界線": "Center Border",
  "有機的な形状": "Organic Shapes",
  "水彩ブロブ": "Watercolor Blobs",
  "紙テクスチャ": "Paper Texture",
  "キラキラの回転": "Glitter Rotation",
  "メタリックな背景オーブ": "Metallic Background Orb",
  "キラキラ星": "Sparkling Stars",
  "メインのグロッシーカード": "Main Glossy Card",
  "グロッシーハイライト": "Glossy Highlights",
  "バブル装飾": "Bubble Decoration",
  "トランジション&リビール集": "Transitions & Reveals Collection",
  "プロのモーショングラフィックスで使用されるトランジション": "Transitions used in professional motion graphics",
  "ブラインドトランジション": "Blinds Transition",
  "縦ブラインド": "Vertical Blinds",
  "ブラインド": "Blinds",
  "前景コンテンツ": "Foreground Content",
  "ボックスリビール": "Box Reveal",
  "グリッド状に表示": "Display in Grid",
  "ボックスマスク": "Box Mask",
  "サークルワイプ": "Circle Wipe",
  "円形に広がる": "Spreads in Circle",
  "新しいコンテンツ": "New Content",
  "エッジのリング": "Edge Ring",
  "斜めスライス": "Diagonal Slice",
  "斜線で切り替え": "Switch on Diagonal Line",
  "エッジライン": "Edge Line",
  "フラッシュトランジション": "Flash Transition",
  "グリッチトランジション": "Glitch Transition",
  "背景シーン": "Background Scene",
  "グリッチスライス": "Glitch Slice",
  "新しいシーン": "New Scene",
  "RGBずれ": "RGB Shift",
  "ラインスイープ": "Line Sweep",
  "複数の線が横切る": "Multiple Lines Cross",
  "リキッドモーフ": "Liquid Morph",
  "液体状に変形": "Morphic Transformation",
  "波形のパス生成": "Wave Path Generation",
  "古いシーン": "Old Scene",
  "液体オーバーレイ": "Liquid Overlay",
  "泡": "Bubble",
  "シャッタートランジション": "Shutter Transition",
  "カメラシャッター風": "Camera Shutter Style",
  "シャッターブレード": "Shutter Blades",
  "中央の円（アパーチャー）": "Center Circle (Aperture)",
  "ズームブラートランジション": "Zoom Blur Transition",
  "古いシーン（ズーム＆ブラー）": "Old Scene (Zoom & Blur)",
  "円（赤）": "Circle (Red)",
  "四角（青）": "Square (Blue)",
  "三角（黄）": "Triangle (Yellow)",
  "線の装飾": "Line Decoration",
  "パターン背景": "Pattern Background",
  "アーチ装飾": "Arch Decoration",
  "太陽モチーフ": "Sun Motif",
  "植物装飾": "Plant Decoration",
  "巨大テキスト背景": "Giant Text Background",
  "境界線ボックス": "Border Box",
  "マーキー風テキスト": "Marquee Style Text",
  "リンクスタイル": "Link Style",
  "カウンター": "Counter",
  "和風/ジャパニーズ": "Japanese Style",
  "自然、アースカラー": "Nature, Earth Colors",
  "太い枠線、原色、影": "Thick Border, Primaries, Shadow",
  "ソフトな凹凸": "Soft Contours",
  "セピア、ノイズ": "Sepia, Noise",
  "装飾線": "Decorative Line",
  "赤いアクセントブロック": "Red Accent Block",
  "サイドテキスト": "Side Text",
  "モダン、クリーン": "Modern, Clean",
  "プロダクトカード": "Product Card",
  "簡易グラフ": "Simple Graph",
  "水彩": "Watercolor",
  "2000年代初頭のグロッシー&メタリック": "Glossy & Metallic of early 2000s"
};

function translateContent(content: string): string {
  let updated = content;
  // Replace each phrase from longest key first to prevent sub-string collision issues
  const sortedKeys = Object.keys(translationMap).sort((a, b) => b.length - a.length);
  
  for (const jp of sortedKeys) {
    const en = translationMap[jp];
    // Global replacement for matching Japanese strings
    updated = updated.split(jp).join(en);
  }
  
  return updated;
}

function processDir(dir: string) {
  const items = fs.readdirSync(dir);
  for (const item of items) {
    const fullPath = path.join(dir, item);
    const stat = fs.statSync(fullPath);
    if (stat.isDirectory()) {
      processDir(fullPath);
    } else if (stat.isFile() && (item.endsWith(".tsx") || item.endsWith(".ts"))) {
      const original = fs.readFileSync(fullPath, "utf-8");
      const translated = translateContent(original);
      if (original !== translated) {
        fs.writeFileSync(fullPath, translated, "utf-8");
        console.log(`Translated file: ${path.relative(rootDir, fullPath)}`);
      }
    }
  }
}

console.log("Starting code comments translation...");
processDir(rootDir);
console.log("Translation complete.");
